# -*- coding: utf-8 -*-
# Jimmy Kha (2022)
"""dataGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7InCE4DldA9ncXQbb7GfW6BnV8d5qAG
"""

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

import math

math.pi*2/math.pi*24

len(([math.sin(x) for x in np.arange(0, 3*math.pi, math.pi/12)]))

len ([math.sin(x) for x in np.arange(0, 2*math.pi, math.pi/13)])

d = {'Time': 240 *  ( [x for x in range(12,24)] + [x for x in range(0, 12)]),
     'Location': 1,
     "Temperature": 240 * ([math.sin(x + 8) for x in np.arange(0, 2*math.pi, math.pi/12)]), 
     'Brightness':  240 *  ([(math.sin(x + 8))  if (math.sin(x + 8)) > 0 else 0 for x in np.arange(0, 2*math.pi, math.pi/12)])}

df = pd.DataFrame(data=d)

df

df.set_index('Time').plot()

